export const NSC_SUBJECTS = [
  'Afrikaans Home Language',
  'Afrikaans First Additional Language',
  'English Home Language',
  'English First Additional Language',
  'IsiZulu Home Language',
  'IsiZulu First Additional Language',
  'IsiXhosa Home Language',
  'IsiXhosa First Additional Language',
  'Sepedi Home Language',
  'Setswana Home Language',
  'Sesotho Home Language',
  'Xitsonga Home Language',
  'Tshivenda Home Language',
  'Mathematics',
  'Mathematical Literacy',
  'Physical Sciences',
  'Life Sciences',
  'Geography',
  'History',
  'Accounting',
  'Economics',
  'Business Studies',
  'Computer Applications Technology',
  'Information Technology',
  'Life Orientation',
  'Engineering Graphics and Design',
  'Agricultural Sciences',
  'Agricultural Technology',
  'Consumer Studies',
  'Hospitality Studies',
  'Tourism',
  'Visual Arts',
  'Music',
  'Dramatic Arts',
  'Religion Studies',
  'Civil Technology',
  'Electrical Technology',
  'Mechanical Technology',
]
